import React, { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import { getInstructorData } from "../../../../services/operations/profileAPI";
import { fetchInstructorCourses } from "../../../../services/operations/courseDetailsAPI";
import { Link } from "react-router-dom";
// import { getInstructorData } from '../../../../services/operations/profileAPI';
import InstructorChart from "./InstructorChart";

const Instructor = () => {
  const { token } = useSelector((state) => state.auth);
  const { user } = useSelector((state) => state.profile);

  const [loading, setLoading] = useState(false);
  const [instructorData, setInstructordata] = useState(null);

  const [courses, setCourses] = useState([]);

  // 2 function call kele getInstructor Data and Instructor all course creeaed by him
  useEffect(() => {
    const fetchInstructorStat = async () => {
      setLoading(true);
      const instructorApiData = await getInstructorData(token);
      console.log(
        " frontend -- Particular Instructor data ==> ",
        instructorApiData
      );

      // instructor che sarv course yethe ahe
      const result = await fetchInstructorCourses(token);
      console.log(" frontend -- Getting isntrucror All courses-->", result);

      if (instructorApiData?.length) {
        setInstructordata(instructorApiData);
      }

      if (result) {
        setCourses(result);
      }

      setLoading(false);
    };
    fetchInstructorStat();
  }, []);

  // we have to display total amount generated by selling course of Insturctor
  // and total student enrolled to that courses

  const totalAmount = instructorData?.reduce(
    (acc, curr) => acc + curr.totalAmountGenerated,
    0
  );

  const totalStudent = instructorData?.reduce(
    (acc, curr) => acc + curr.totalStudentEnrolled,
    0
  );

  return (
    <div className="text-richblack-5">
      {/* Header */}
      <div className="mb-6">
        <h1 className="text-2xl font-semibold">Hi {user?.firstName} 👋</h1>
        <p className="text-richblack-200">Let’s start something new</p>
      </div>

      {loading ? (
        <div className="spinner" />
      ) : courses?.length > 0 ? (
        <div className="flex flex-col gap-8">
          {/* Chart + Stats */}
          <div className="flex flex-col lg:flex-row gap-6">
            {/* Chart */}
            <div className="w-full lg:w-4/5 bg-richblack-800 rounded-lg p-6">
              <InstructorChart courses={instructorData} />
            </div>

            {/* Stats */}
            <div className="w-full lg:w-1/5 bg-richblack-800 rounded-lg p-6 flex flex-col gap-4">

              <p className="text-3xl font-semibold">Statistics</p>

              <div className="flex flex-col space-y-3 pb-2 mt-5">
                <p className="text-richblack-100">Total Courses</p>
                <p className="font-bold text-3xl">{courses?.length}</p>
              </div>

              <div className="flex flex-col space-y-3 justify-between border-b border-richblack-200 pb-2">
                <p className="text-richblack-100">Total Students</p>
                <p className="font-bold text-3xl">{totalStudent}</p>
              </div>

              <div className="flex flex-col justify-between space-y-3 ">
                <p className="text-richblack-100">Total Income</p>
                <p className="font-bold text-3xl">Rs. {totalAmount}</p>
              </div>
            </div>
          </div>

          {/* Courses */}
          <div className="bg-richblack-800 rounded-lg p-6">
            <div className="flex justify-between items-center mb-4">
              <p className="text-lg font-semibold">Your Courses</p>
              <Link
                to="/dashboard/my-courses"
                className="text-yellow-50 text-sm hover:underline"
              >
                View All
              </Link>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3   gap-6 ">
              {courses.slice(0, 3).map((course, index) => (
                <div
                  key={index}
                  className="bg-richblack-900 rounded-lg overflow-hidden shadow-md"
                >
                  <img
                    src={course.thumbnail}
                    alt="course"
                    className="h-40 w-full object-cover"
                  />
                  <div className="p-4">
                    <p className="font-medium">{course.courseName}</p>
                    <div className="flex justify-between text-sm text-richblack-300 mt-2">
                      <span>{course.studentsEnrolled?.length} students</span>
                      <span>Rs. {course.price}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      ) : (
        <div className="bg-richblack-800 p-6 rounded-lg">
          <p>You haven’t created any course yet</p>
          <Link
            to="/dashboard/addCourse"
            className="text-yellow-50 underline ml-2"
          >
            Create Course
          </Link>
        </div>
      )}
    </div>
  );
};

export default Instructor;
