import React, { useEffect, useState } from 'react'
import { useSelector } from 'react-redux';
import {getInstructorData} from '../../../../services/operations/profileAPI';
import { fetchInstructorCourses } from '../../../../services/operations/courseDetailsAPI';
import { Link } from 'react-router-dom';
// import { getInstructorData } from '../../../../services/operations/profileAPI';
import InstructorChart from './InstructorChart';

const Instructor = () => {

    const {token} = useSelector((state)=> state.auth);
    const {user }= useSelector((state)=>state.profile);


    const [laoding,setLoading] = useState(false);
    const [instructorData,setInstructordata] = useState(null);

    const[courses,setCourses] = useState([]);

    // 2 function call kele getInstructor Data and Instructor all course creeaed by him 
    useEffect(()=>{
        const fetchInstructorStat = async()=>{
            setLoading(true);
            const instructorApiData = await getInstructorData(token);
            console.log(" frontend -- Particular Instructor data ==> ",instructorApiData);
            
            // instructor che sarv course yethe ahe 
            const result = await fetchInstructorCourses(token);
            console.log(" frontend -- Getting isntrucror All courses-->",result);


            if(instructorApiData.length){
                setInstructordata(instructorApiData);   
            };

            if(result){
                setCourses(result);
            };

            setLoading(false);

        }
        fetchInstructorStat();
    },[]);


    // we have to display total amount generated by selling course of Insturctor 
    // and total student enrolled to that courses 

    const totalAmount = instructorData?.reduce((acc,curr)=> acc +curr.totalAmountGenerated,0);

    const totalStudent = instructorData?.reduce((acc,curr)=> acc +  curr.totalStudentEnrolled,0)



  return (
    <div className='text-richblack-5'> 

        <div>
        <h1> hi {user?.firstName} </h1>
        <p> Let's Start Something New </p>
        </div>
        
        {/* chart and stats */}
        {
            laoding ? 
            (<div className='spinner'> </div>):courses.length>0 ?
            (
                <div>
                    

                <div>
                <div>
                    {/* Instructor chart  
                    */}

                    <InstructorChart courses={instructorData}/>
                    
                    <div>
                        {/* other data */}
                        <p> Statistics</p>
                        <div>

                            <p>Total courses </p> 
                            <p>{courses.length} </p>
                        </div>

                        <div>
                            <p>Total Student </p>
                            <p>
                                {totalStudent}
                            </p>
                        </div>

                        {/*Totla income  */}
                        <div>
                            <p>Total Income </p>
                            <p> {totalAmount}</p>
                        </div>

                    </div>
                </div>
            </div>

            <div>
                {/*render 3 cards   */}
                <div>
                    <p> Your Courses </p> 
                    <Link to="/dashboard/my-courses">
                        <p> View All </p>
                    </Link>
                        
                </div>
                <div>
                    {
                        courses.slice(0,3).map((course,index)=>(
                            <div key={index}>
                                <img src={course.thumbnail } alt='course img'/>
                                <div>
                                    <p> {course.courseName}</p>

                                    <div>
                                        <p> {course.studentsEnrolled?.length} students</p>

                                        <p>|</p>
                                        <p> RS {course.price}</p>
                                    </div>
                                </div>
                            </div>
                        ))
                    }
                </div>

            </div>

                </div>
            
        )
            
            :(<div>You Have not created any course yet 

                <Link to="/dashboard/addCourse">
                    Create Course 
                </Link>
            </div>)
        }
    </div>
  )
}

export default Instructor